CREATE TABLE tb_store_supplier(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
cnpj VARCHAR(14) NOT NULL,
name VARCHAR(255) NOT NULL,
phonenumber VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
logradouro VARCHAR(255) NOT NULL,
complemento VARCHAR(255)  NULL,
bairro VARCHAR(255) NOT NULL,
localidade VARCHAR(255) NOT NULL,
uf VARCHAR(255)NOT NULL);